### PR TITLE
Updated italian translation

### PR DESCRIPTION
**Pull request by paolobenve**
There were many translation not exact

### CODE REVIEW

**Comment by dgearhart** [comment]
Grazie!

**Comment by paolobenve** [comment]
when will changes propagate in mapzen routing indications?

**Comment by kevinkreiser** [comment]
we hope to do a release early next week, monday most likely

**Comment by paolobenve** [comment]
thank you

**Comment by dgearhart** [comment]
@paolobenve, your changes have been released

**Pull request merged**
