### PR TITLE
translation to Spanish

### PR DESCRIPTION
**Pull request by rossanag**
I had problems running the tests, as I was asked to make a PR with the files, I did it. Hope it helps.

### CODE REVIEW

**Comment by dgearhart** [comment]
@rossanag thank you
I submitted a PR to your fork that fixes the test isues

**Comment by dgearhart** [comment]
@rossanag thank you!

**Comment by darkwizzard** [comment]
@rossanag Thank you so much! I can see that the pull request is closed. 

So, when can i find spanish in Valhalla mapzen json ?

Regards.

**Comment by rossanag** [comment]
The translation it is availlable in Odin's github. I'd like to help but I have no idea since I barely use Mapzen,  isn't it configurable? Maybe is up to Mapzen staff to say that, in case they need to update something.

**Comment by dgearhart** [comment]
@rossanag @darkwizzard 
If you are using Valhalla locally - you can get the latest code and use it now - example URL:
http://localhost:8002/route?json={%22locations%22:[{%22lat%22:40.730930,%22lon%22:-73.991379,%22street%22:%22Wanamaker%20Place%22},{%22lat%22:40.749706,%22lon%22:-73.991562,%22street%22:%22Penn%20Plaza%22}],%22costing%22:%22multimodal%22,%22directions_options%22:{%22units%22:%22miles%22,%22language%22:%22es-ES%22},%22date_time%22:{%22type%22:1,%22value%22:%222016-08-23T08:00%22}}

If you are using the Mapzen Turn-by-Turn service - we hoping to update our production servers next week.

Thanks to both of you for your contributions and interest in Valhalla

Here is partial example Spanish response:
spanish_example

**Comment by darkwizzard** [comment]
@dgearhart Thanks for your answer I would try it the next week with mapzen turn by turn service.

**Comment by dgearhart** [comment]
@rossanag @darkwizzard 
Spanish has been pushed to production - thank you
spanish_osm_example

**Comment by rossanag** [comment]
Nice to know, glad to help :) . Any suggestion will be appreciated. I will check the translation for eventual corrections.

**Pull request merged**
