### PR TITLE
use less sed to avoid breaking on macs

### PR DESCRIPTION
**Pull request by kevinkreiser**
something about regex on the mac version of sed is not quite the same as in ubuntu. so we avoid the problem by using less complex means of accomplishing the same thing.

@ericrwolfe this should fix your mac builds or at least get you closer to building ;)

### CODE REVIEW

**Comment by gknisely** [comment]
:ship:

**Comment by ericrwolfe** [comment]
Had to install ja, but looks like everything compiling.

Getting a silent error, does this matter?

```
$ make
 PROTOC proto/trippath.proto
 PROTOC proto/tripdirections.proto
 PROTOC proto/directions_options.proto
cd locales && ./make_locales.sh *.json > ../src/odin/locales.h && cd -
Can't open UTF-8: No such file or directory
make: [src/odin/locales.h] Error 4 (ignored)
/Applications/Xcode.app/Contents/Developer/usr/bin/make  all-am
  CXX      src/proto/libvalhalla_odin_la-trippath.pb.lo
  CXX      src/proto/libvalhalla_odin_la-tripdirections.pb.lo
```

**Comment by kevinkreiser** [comment]
@ericrwolfe yeah that means that your tests will fail because you dont have localedef and all the stuff to build locales (not sure how to get that on a mac) but the code should work

**Comment by ericrwolfe** [comment]
Yup, 2 of the tests are failing. I'll have to circle back on the localedef stuff, doesn't look like theres a package immediately available on homebrew, but this should give me more than enough to work with.

**Pull request merged**
